import type { Event } from "../types";

// デモ・開発用のサンプルイベントデータ
// events.json が未生成またはオフライン時のフォールバック用
export const SAMPLE_EVENTS: Event[] = [
  // --- FIFA W杯 2026 ---
  {
    id: 1,
    lg: "wc2026",
    date: "2026-06-14",
    day: "土",
    time: "05:00",
    title: "日本 vs ブラジル",
    cat: "グループステージ",
    casts: ["dazn", "ntv"],
    result: {
      status: "finished",
      score: { home: 2, away: 1, winner: "home" },
      teams: {
        home: { id: 841, crest: "https://crests.football-data.org/841.svg" },
        away: { id: 764, crest: "https://crests.football-data.org/764.svg" },
      },
    },
  },
  {
    id: 2,
    lg: "wc2026",
    date: "2026-06-14",
    day: "土",
    time: "26:00",
    title: "フランス vs スペイン",
    cat: "グループステージ",
    casts: ["dazn", "nhkbs"],
    result: {
      status: "finished",
      score: { home: 1, away: 1, winner: "draw" },
      penalties: { home: 5, away: 4 },
      teams: {
        home: { id: 760, crest: "https://crests.football-data.org/760.svg" },
        away: { id: 759, crest: "https://crests.football-data.org/759.svg" },
      },
    },
  },
  {
    id: 3,
    lg: "wc2026",
    date: "2026-06-18",
    day: "水",
    time: "05:00",
    title: "ボスニア vs アラブ",
    cat: "グループステージ",
    casts: ["dazn"],
    result: {
      status: "finished",
      score: { home: 2, away: 0, winner: "home" },
      teams: {
        home: { id: 1060, crest: "https://crests.football-data.org/bosnia.svg" },
        away: { id: 1146, crest: "https://crests.football-data.org/1146.svg" },
      },
    },
  },
  {
    id: 30,
    lg: "wc2026",
    date: "2026-06-15",
    day: "日",
    time: "20:00",
    title: "サウジアラビア vs ニュージーランド",
    cat: "グループステージ",
    casts: ["dazn"],
    result: {
      status: "finished",
      score: { home: 1, away: 1, winner: "draw" },
      penalties: { home: 4, away: 2 },
      teams: {
        home: { id: 793, crest: "https://crests.football-data.org/793.svg" },
        away: { id: 1081, crest: "https://crests.football-data.org/1081.svg" },
      },
    },
  },
  {
    id: 4,
    lg: "wc2026",
    date: "2026-06-22",
    day: "日",
    time: "05:00",
    title: "日本 vs セネガル",
    cat: "グループステージ",
    casts: ["dazn", "fuji"],
  },

  // --- Jリーグ ---
  {
    id: 11,
    lg: "jleague",
    date: "2026-06-14",
    day: "土",
    time: "19:00",
    title: "浦和レッズ vs 鹿島アントラーズ",
    cat: "J1 第18節",
    casts: ["dazn"],
  },
  {
    id: 12,
    lg: "jleague",
    date: "2026-06-14",
    day: "土",
    time: "19:00",
    title: "FC東京 vs 川崎フロンターレ",
    cat: "J1 第18節",
    casts: ["dazn"],
  },
  {
    id: 13,
    lg: "jleague",
    date: "2026-06-15",
    day: "日",
    time: "18:00",
    title: "横浜FM vs ガンバ大阪",
    cat: "J1 第18節",
    casts: ["dazn", "nhkbs"],
  },
  {
    id: 14,
    lg: "jleague",
    date: "2026-06-21",
    day: "土",
    time: "19:00",
    title: "ヴィッセル神戸 vs 名古屋",
    cat: "J1 第19節",
    casts: ["dazn"],
  },

  // --- 海外サッカー ---
  {
    id: 21,
    lg: "intl",
    date: "2026-06-14",
    day: "土",
    time: "23:00",
    title: "レアル・マドリード vs バルセロナ",
    cat: "親善試合",
    casts: ["wowow", "abema"],
  },
  {
    id: 22,
    lg: "intl",
    date: "2026-06-15",
    day: "日",
    time: "25:00",
    title: "マンチェスターC vs アーセナル",
    cat: "親善試合",
    casts: ["unext", "abema"],
  },
  {
    id: 23,
    lg: "intl",
    date: "2026-06-20",
    day: "土",
    time: "27:00",
    title: "インテル vs ユヴェントス",
    cat: "親善試合",
    casts: ["dazn"],
  },

  // --- F1 ---
  {
    id: 31,
    lg: "f1",
    date: "2026-06-13",
    day: "金",
    time: "02:30",
    title: "カナダGP フリー走行",
    cat: "FP1/FP2",
    casts: ["dazn", "sky"],
  },
  {
    id: 32,
    lg: "f1",
    date: "2026-06-14",
    day: "土",
    time: "04:00",
    title: "カナダGP 予選",
    cat: "予選",
    casts: ["dazn", "sky"],
  },
  {
    id: 33,
    lg: "f1",
    date: "2026-06-15",
    day: "日",
    time: "03:00",
    title: "カナダGP 決勝",
    cat: "決勝",
    casts: ["dazn", "fuji", "sky"],
    result: {
      status: "finished",
      standings: [
        { position: 1, points: 25, driver: "Max Verstappen", constructor: "Red Bull", status: "Finished" },
        { position: 2, points: 18, driver: "Lando Norris", constructor: "McLaren", status: "Finished" },
        { position: 3, points: 15, driver: "Oscar Piastri", constructor: "McLaren", status: "Finished" },
      ],
    },
  },

  // --- オリンピック（サンプル）---
  {
    id: 41,
    lg: "olympic",
    date: "2026-07-25",
    day: "土",
    time: "20:00",
    title: "開会式",
    cat: "式典",
    casts: ["nhk", "nhkbs"],
  },
  {
    id: 42,
    lg: "olympic",
    date: "2026-07-26",
    day: "日",
    time: "19:30",
    title: "体操 男子団体 決勝",
    cat: "体操",
    casts: ["ntv", "sky"],
  },
];
